[general]
log_level=4

[postgresql]
dsn="postgres://loraserver_ns:loraserver_ns@localhost/loraserver_ns?sslmode=disable"

[network_server]
net_id="000000"

  [network_server.band]
  name="AS_920_923"

  [[network_server.network_settings.extra_channels]]
  frequency=923200000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=923400000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=922200000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=922400000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=922600000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=922800000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=923000000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=922000000
  min_dr=0
  max_dr=5
