[general]
log_level=4

[postgresql]
dsn="postgres://loraserver_ns:loraserver_ns@localhost/loraserver_ns?sslmode=disable"

[network_server]
net_id="000000"

  [network_server.band]
  name="KR_920_923"

  [[network_server.network_settings.extra_channels]]
  frequency=922100000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=922300000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=922500000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=922700000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=922900000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=923100000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=923300000
  min_dr=0
  max_dr=5
